### ISSUE TITLE
RuntimeError: Input must be 13 bits binary string.

### ISSUE THREAD

**Issue by Mianduibaba** [open-aviation/pyopensky#21]
when i downloading data from opensky, by use function(get) of procedure (ehshelper.py).

data_ehs =  get ( icao24 = None, start = '2023-03-01 09:30:00' , end = '2023-03-01 10:30:00' , bound= [48,-2,56,10],)

and rise the follow error :
RuntimeError: Input must be 13 bits binary string
Traceback (most recent call last):
  File "E:\download\data\3_1_0930-1030\ehsraw_read.py", line 27, in ehs_decode
    commb.loc[commb.DF == 21, "squawk"] = commb.loc[
  File "E:\anac\envs\mp\lib\site-packages\pandas\core\series.py", line 4630, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "E:\anac\envs\mp\lib\site-packages\pandas\core\apply.py", line 1025, in apply
    return self.apply_standard()
  File "E:\anac\envs\mp\lib\site-packages\pandas\core\apply.py", line 1076, in apply_standard
    mapped = lib.map_infer(
  File "pandas\_libs\lib.pyx", line 2834, in pandas._libs.lib.map_infer
  File "pyModeS\\c_common.pyx", line 238, in pyModeS.c_common.idcode
  File "pyModeS\\c_common.pyx", line 243, in pyModeS.c_common.idcode
  File "pyModeS\\c_common.pyx", line 253, in pyModeS.c_common.squawk

And this issue not always happend , I try to fix this but I don't know Is it a bug of pyopensky or pymodes .It looks like something wrong when decodeing "squawk".I can't find the version that I download on github , but there are the same procedure  in "decode_ehs.py" , Therefore, I write this asking for help , thank you professor.

**Comment by xoolive** [comment]
Closing issues with new release of pyopensky, please open a new issue if still applicable with pyopensky>2.0
